export enum ROLES {
  USER = 'USER',
  MODERATOR = 'MODERATOR',
  ADMIN = 'ADMIN'
}

export enum INTERFACE_TYPE {
  DARK = 'DARK',
  LIGHT = 'LIGHT'
}

export enum PROBLEM_AUDIT_ACTION {
  THUMB_UP = 'THUMB_UP',
  THUMB_DOWN = 'THUMB_DOWN'
}
